sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t harrisleesh/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true harrisleesh/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-762224883854"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key_id: $AWS_SECRET_ACCESS_KEY